### ISSUE TITLE
Open Window while raining

### ISSUE THREAD

**Issue by mqtt-fan** [MiSchroe/klf-200-api#10]
Hi,

with the "display remote" I can open my window even if it's raining. Is there a possibility to do this with klf-200-api?

**Comment by MiSchroe** [comment]
I haven't tried it out, but it could be possible if you send a `GW_COMMAND_SEND_REQ` with the `PriorityLevelLock` parameter set to `UsePriorityLevelLock` and the parameter `PriorityLevels` set to an array of 8 PriorityLevelInformation = `[PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.Disable, PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.KeepCurrent, PriorityLevelInformation.KeepCurrent]`. This should lock out the rain sensor which operates on the priority level 1. Using the parameter `LockTime` you can set the time for the lock. The lock time must be a multiple of 30 minutes and may not exceed 7560 minutes or use `Infinity` for an infinite lock time.

You first create the command object by instantiating the a new object of the class `GW_COMMAND_SEND_REQ` and provide the necessary parameters. Second, you send the command with the `sendFrameAsync` method of the `Connection` object.
