### ISSUE TITLE
How to get position?

### ISSUE THREAD

**Issue by jslettengren** [MiSchroe/klf-200-api#14]
I've been able to use the API with very rudimentary open/close of blinds and windows. I want to improve the functionality, but in order to do that I would need to read the current positions of the devices.

My ts skills are close to none, but I figure that something like below should work. Output from running the below is: `NaN`.

Could anyone give me a hint on what I'm doing wrong? I'd really appreciate it.

```
    const window = myProducts.findByName("Window left");
    if (window) {
        
        var p = window.CurrentPosition;
        console.log(p);

    } else {
        throw(new Error("Could not find window left."));
    }
```

**Comment by MiSchroe** [comment]
Your code should work. This is a more complete example:
````typescript
    const products = await Products.createProductsAsync(conn);
    console.log("Products loaded");
    const prodFensterBuero = products.findByName("Fenster Büro");

    if (prodFensterBuero) {
        console.log("Window found");
        var p = prodFensterBuero.CurrentPosition;
        console.log(p);
    }
    else {
        console.log("Fenster nicht gefunden");
    }
````

Could you try with CurrentPositionRaw instead? It should return 51200 for a closed window.

**Comment by jslettengren** [comment]
Hmm. That's strange. For CurrentPositionRaw, I get 63487 for both the blinds and the windows whatever the true positions are. So the question is, what does 0xF7FF mean?

Thanks for taking your time!

**Comment by MiSchroe** [comment]
`0xF7FF` means 'No feedback value known'. Have you tried to enable the house status monitor first? By default it's set off. If you set it on you will receive notifactions for every change. Additionally, the status of the products will be scanned in regular intervals.

````typescript
const gw = new Gateway(conn);
await gw.enableHouseStatusMonitorAsync();
````

You have to do this only once, the service stays activated after a reboot of the KLF-200. It will request the current status of all registered products 2mins after reboot and then every 15min to 24h, depending on the device type. See the official documentation for additional help on this.

**Comment by jslettengren** [comment]
That did the trick! Thank you once again!
