### ISSUE TITLE
Investigate compatibility with new KLF-200 firmware

### ISSUE THREAD

**Issue by altery** [MiSchroe/klf-200-api#3]
Velux released a new firmware (0.2.0.0.71.0) for the KLF-200. Unfortunately, there are no release notes. It would be important to know, if this library is still compatible with the new firmware.

**Comment by mqtt-fan** [comment]
Check out this:

https://www.velux.com/api/klf200

After Updating there is no web interface anymore. But a powerful API is now available

**Comment by Julius2342** [comment]
This is a great move. But I wonder why-on-earth they have decided to use a binary protocol?

Cleartext protocol to be precise.

And the code of their demo is horrible :)

**Comment by altery** [comment]
Thanks for the link! That is certainly great news. As far as I know, this is the first generic io-Homecontrol gateway, which makes those devices suddenly much more attractive.
