### ISSUE TITLE
 Error: Invalid frame structure.

### ISSUE THREAD

**Issue by dktjsp** [MiSchroe/klf-200-api#31]
Hi i have this error when i try to change position

`(node:5021) UnhandledPromiseRejectionWarning: Error: Invalid frame structure.
    at cfmHandler.klfProtocol.on (/Users/spichtj/Desktop/velux/node_modules/klf-200-api/dist/connection.js:162:40)
    at listeners.forEach (/Users/spichtj/Desktop/velux/node_modules/klf-200-api/dist/utils/TypedEvent.js:25:50)
`

I'm logged in but this command fails, could you help me ? 

Thanks

**Comment by dktjsp** [comment]
Here is the frame

```
GW_COMMAND_SEND_REQ {
  Command: 768,
  offset: 3,
  BufferSize: 66,
  data:
   <Buffer 45 03 00 00 00 01 03 00 00 00 be 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 ... >,
  SessionID: 0,
  Nodes: 0,
  MainValue: 48640,
  PriorityLevel: 3,
  CommandOriginator: 1,
  ParameterActive: 0,
  FunctionalParameters: [],
  PriorityLevelLock: 0,
  PriorityLevels: [],
  LockTime: Infinity }
```

**Comment by MiSchroe** [comment]
The error will be generated by the KLF-200 itself, so something at your frame is wrong.
Try the sample in the README.MD.

**Comment by dktjsp** [comment]
I found out the issue , thanks
