### ISSUE TITLE
install of klf-200-api on raspberry pi is not successful

### ISSUE THREAD

**Issue by jerome0711** [MiSchroe/klf-200-api#9]
Hello,

running the install of klf-200-api on raspberry pi is not successful. Are there missing bits in my installation ?

Thank you

See below the output of installation.

sudo npm install klf-200-api --save
(node:9174) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.42-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "klf-200-api" "--save"
npm ERR! cwd /home/pi/script
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/script/npm-debug.log
npm ERR! not ok code 0

**Comment by MiSchroe** [comment]
The issue seems to be related to npm/node. You are using an old version. Please try to upgrade or uninstall and re-install node and npm.

**Comment by jerome0711** [comment]
Hello,

Thank you for the response. I upgraded node and npm. At installation of 
klf-200-api I had some warnings that I did not considered further:

* npm install klf-200-api --save*
npm WARN saveError ENOENT: no such file or directory, open 
'/home/pi/script/package.json'
npm notice created a lockfile as package-lock.json. You should commit 
this file.
npm WARN enoent ENOENT: no such file or directory, open 
'/home/pi/script/package.json'
npm WARN script No description
npm WARN script No repository field.
npm WARN script No README data
npm WARN script No license field.

+ klf-200-api@3.0.0
added 3 packages from 3 contributors and audited 3 packages in 3.381s
found 0 vulnerabilities


But when running the script, import of klf module seems to be an 
issue... My appologies but I am a newbie in javascript and nodejs...

*node my_klf_script.js*
(node:22556) Warning: To load an ES module, set "type": "module" in the 
package.json or use the .mjs extension.
/home/pi/script/klf.js:1
import { Connection, Products, Product } from "klf-200-api";
^^^^^^

SyntaxError: Cannot use import statement outside a module
     at wrapSafe (internal/modules/cjs/loader.js:1050:16)
     at Module._compile (internal/modules/cjs/loader.js:1098:27)
     at Object.Module._extensions..js 
(internal/modules/cjs/loader.js:1167:10)
     at Module.load (internal/modules/cjs/loader.js:983:32)
     at Function.Module._load (internal/modules/cjs/loader.js:891:14)
     at Function.executeUserEntryPoint [as runMain] 
(internal/modules/run_main.js:71:12)
     at internal/main/run_main_module.js:17:47
Br

Jerome


Le 09/12/2019 à 17:52, MiSchroe a écrit :

**Comment by MiSchroe** [comment]
https://nodejs.org/api/esm.html#esm_code_import_code_statements

Try using require instead of import if you don't write your own module. Please check other resources for getting basic node js/javascript/typescript help.
